using Microsoft.EntityFrameworkCore;
namespace AiTrading.Infrastructure.Persistence;
public sealed class TradingDbContext(DbContextOptions<TradingDbContext> options) : DbContext(options)
{
 public DbSet<PortfolioRecord> Portfolios=>Set<PortfolioRecord>(); public DbSet<OrderRecord> Orders=>Set<OrderRecord>(); public DbSet<FillRecord> Fills=>Set<FillRecord>(); public DbSet<PositionRecord> Positions=>Set<PositionRecord>(); public DbSet<AlertRecord> Alerts=>Set<AlertRecord>(); public DbSet<MarketDataSnapshotRecord> MarketDataSnapshots=>Set<MarketDataSnapshotRecord>(); public DbSet<HistoricalCandleRecord> HistoricalCandles=>Set<HistoricalCandleRecord>(); public DbSet<BacktestRunRecord> BacktestRuns=>Set<BacktestRunRecord>(); public DbSet<BacktestTradeAuditRecord> BacktestTradeAudits=>Set<BacktestTradeAuditRecord>(); public DbSet<BacktestRiskAuditRecord> BacktestRiskAudits=>Set<BacktestRiskAuditRecord>(); public DbSet<PaperTradingSessionRecord> PaperTradingSessions=>Set<PaperTradingSessionRecord>(); public DbSet<PaperTradingEventAuditRecord> PaperTradingEventAudits=>Set<PaperTradingEventAuditRecord>(); public DbSet<PredictionRecordEntity> Predictions=>Set<PredictionRecordEntity>(); public DbSet<PredictionOutcomeEntity> PredictionOutcomes=>Set<PredictionOutcomeEntity>();
 protected override void OnModelCreating(ModelBuilder m)
 {
  m.Entity<PortfolioRecord>(e=>{e.ToTable("portfolios");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Cash).HasPrecision(20,4);e.Property(x=>x.RealizedPnl).HasPrecision(20,4);e.Property(x=>x.Version).IsConcurrencyToken();e.HasIndex(x=>x.Version);});
  m.Entity<OrderRecord>(e=>{e.ToTable("orders");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.IdempotencyKey).HasMaxLength(128).IsRequired();e.HasIndex(x=>x.IdempotencyKey).IsUnique();e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.InstrumentToken).HasMaxLength(100);e.Property(x=>x.Side).HasMaxLength(16).IsRequired();e.Property(x=>x.ExecutionMode).HasMaxLength(16).IsRequired();e.Property(x=>x.Status).HasMaxLength(32).IsRequired();e.Property(x=>x.StrategyVersion).HasMaxLength(64).IsRequired();e.Property(x=>x.LimitPrice).HasPrecision(20,4);});
  m.Entity<FillRecord>(e=>{e.ToTable("fills");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.OrderId).HasColumnType("char(36)");e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.Side).HasMaxLength(16).IsRequired();e.Property(x=>x.ExecutionProvider).HasMaxLength(32).IsRequired();e.Property(x=>x.FillPrice).HasPrecision(20,4);e.HasOne<OrderRecord>().WithMany().HasForeignKey(x=>x.OrderId).OnDelete(DeleteBehavior.Restrict);e.HasIndex(x=>x.OrderId).IsUnique();});
  m.Entity<PositionRecord>(e=>{e.ToTable("positions");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.PortfolioId).HasColumnType("char(36)");e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.InstrumentToken).HasMaxLength(100);e.Property(x=>x.AverageEntryPrice).HasPrecision(20,4);e.Property(x=>x.CurrentMarketPrice).HasPrecision(20,4);e.Property(x=>x.StopLoss).HasPrecision(20,4);e.HasIndex(x=>new{x.PortfolioId,x.Symbol}).IsUnique();e.HasOne<PortfolioRecord>().WithMany().HasForeignKey(x=>x.PortfolioId).OnDelete(DeleteBehavior.Cascade);});
  m.Entity<AlertRecord>(e=>{e.ToTable("alerts");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.PositionId).HasColumnType("char(36)");e.Property(x=>x.Rule).HasMaxLength(64).IsRequired();e.Property(x=>x.Severity).HasMaxLength(16).IsRequired();e.Property(x=>x.Message).HasMaxLength(1000).IsRequired();e.Property(x=>x.EvaluationBucket).HasMaxLength(64).IsRequired();e.Property(x=>x.Symbol).HasMaxLength(100);e.HasIndex(x=>new{x.PositionId,x.Rule,x.EvaluationBucket}).IsUnique();e.HasOne<PositionRecord>().WithMany().HasForeignKey(x=>x.PositionId).OnDelete(DeleteBehavior.SetNull);});
  m.Entity<MarketDataSnapshotRecord>(e=>{e.ToTable("market_data_snapshots");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.InstrumentToken).HasMaxLength(100);e.Property(x=>x.Provider).HasMaxLength(64).IsRequired();e.Property(x=>x.Exchange).HasMaxLength(32).IsRequired();e.Property(x=>x.Open).HasPrecision(20,4);e.Property(x=>x.High).HasPrecision(20,4);e.Property(x=>x.Low).HasPrecision(20,4);e.Property(x=>x.Close).HasPrecision(20,4);e.Property(x=>x.LastTradedPrice).HasPrecision(20,4);e.HasIndex(x=>new{x.Symbol,x.ProviderTimestamp});});
  m.Entity<HistoricalCandleRecord>(e=>{e.ToTable("historical_candles");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.InstrumentToken).HasMaxLength(100).IsRequired();e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.Interval).HasMaxLength(16).IsRequired();e.Property(x=>x.Source).HasMaxLength(64).IsRequired();e.Property(x=>x.Timestamp).HasColumnType("datetime(6)");e.Property(x=>x.ReceivedAt).HasColumnType("datetime(6)");e.Property(x=>x.Open).HasPrecision(20,4);e.Property(x=>x.High).HasPrecision(20,4);e.Property(x=>x.Low).HasPrecision(20,4);e.Property(x=>x.Close).HasPrecision(20,4);e.HasIndex(x=>new{x.Symbol,x.InstrumentToken,x.Interval,x.Timestamp,x.Source}).IsUnique();});
  m.Entity<BacktestRunRecord>(e=>{e.ToTable("backtest_runs");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.Interval).HasMaxLength(16).IsRequired();e.Property(x=>x.StrategyVersion).HasMaxLength(64).IsRequired();e.Property(x=>x.StartingCash).HasPrecision(20,4);e.Property(x=>x.QuantityPerTrade).IsRequired();e.Property(x=>x.FeeRate).HasPrecision(12,8);e.Property(x=>x.SlippageBasisPoints).HasPrecision(12,4);e.Property(x=>x.ResultJson).HasColumnType("longtext");e.HasIndex(x=>x.CreatedAt);});
  m.Entity<BacktestTradeAuditRecord>(e=>{e.ToTable("backtest_trade_audits");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.BacktestRunId).HasColumnType("char(36)");e.Property(x=>x.Side).HasMaxLength(16).IsRequired();e.Property(x=>x.Quantity).IsRequired();e.Property(x=>x.RiskDecision).HasMaxLength(32).IsRequired();e.Property(x=>x.RiskReason).HasMaxLength(1000);e.Property(x=>x.Price).HasPrecision(20,4);e.Property(x=>x.Fee).HasPrecision(20,4);e.HasIndex(x=>new{x.BacktestRunId,x.Timestamp});e.HasOne<BacktestRunRecord>().WithMany().HasForeignKey(x=>x.BacktestRunId).OnDelete(DeleteBehavior.Cascade);});
  m.Entity<BacktestRiskAuditRecord>(e=>{e.ToTable("backtest_risk_audits");e.HasKey(x=>x.Id);e.Property(x=>x.BacktestRunId).HasColumnType("char(36)");e.Property(x=>x.Decision).HasMaxLength(32).IsRequired();e.Property(x=>x.Reason).HasMaxLength(1000);e.Property(x=>x.AvailableCash).HasPrecision(20,4);e.HasIndex(x=>new{x.BacktestRunId,x.Timestamp});e.HasOne<BacktestRunRecord>().WithMany().HasForeignKey(x=>x.BacktestRunId).OnDelete(DeleteBehavior.Cascade);});
  m.Entity<PaperTradingSessionRecord>(e=>{e.ToTable("paper_trading_sessions");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.SymbolsJson).HasColumnType("longtext").IsRequired();e.Property(x=>x.Interval).HasMaxLength(16).IsRequired();e.Property(x=>x.StrategyVersion).HasMaxLength(64).IsRequired();e.Property(x=>x.StartingCash).HasPrecision(20,4);e.Property(x=>x.Status).HasMaxLength(16).IsRequired();});
  m.Entity<PaperTradingEventAuditRecord>(e=>{e.ToTable("paper_trading_event_audits");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.SessionId).HasColumnType("char(36)");e.Property(x=>x.OrderId).HasColumnType("char(36)");e.Property(x=>x.EventId).HasMaxLength(128).IsRequired();e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.RiskDecision).HasMaxLength(32).IsRequired();e.Property(x=>x.RiskReason).HasMaxLength(1000).IsRequired();e.Property(x=>x.FillPrice).HasPrecision(20,4);e.HasIndex(x=>new{x.SessionId,x.CreatedAt});e.HasIndex(x=>new{x.SessionId,x.EventId}).IsUnique();});
  m.Entity<PredictionRecordEntity>(e=>{e.ToTable("predictions");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.Symbol).HasMaxLength(100).IsRequired();e.Property(x=>x.Horizon).HasMaxLength(32).IsRequired();e.Property(x=>x.ExpectedReturn).HasPrecision(20,8);e.Property(x=>x.ProbabilityPositive).HasPrecision(8,6);e.Property(x=>x.Confidence).HasPrecision(8,6);e.Property(x=>x.ModelVersion).HasMaxLength(64).IsRequired();e.Property(x=>x.DataTimestamp).HasColumnType("datetime(6)");e.Property(x=>x.RecordedAt).HasColumnType("datetime(6)");e.HasIndex(x=>new{x.Symbol,x.DataTimestamp});});
  m.Entity<PredictionOutcomeEntity>(e=>{e.ToTable("prediction_outcomes");e.HasKey(x=>x.PredictionId);e.Property(x=>x.PredictionId).HasColumnType("char(36)");e.Property(x=>x.ActualReturn).HasPrecision(20,8);e.Property(x=>x.OutcomeTimestamp).HasColumnType("datetime(6)");e.HasOne<PredictionRecordEntity>().WithOne().HasForeignKey<PredictionOutcomeEntity>(x=>x.PredictionId).OnDelete(DeleteBehavior.Cascade);e.HasIndex(x=>x.OutcomeTimestamp);});
  m.Entity<MonitoringRunRecord>(e=>{e.ToTable("monitoring_runs");e.HasKey(x=>x.Id);e.Property(x=>x.Id).HasColumnType("char(36)");e.Property(x=>x.StartedAt).HasColumnType("datetime(6)");e.Property(x=>x.CompletedAt).HasColumnType("datetime(6)");e.Property(x=>x.Status).HasMaxLength(32).IsRequired();});
 }
}
public sealed class PortfolioRecord { public Guid Id{get;set;} public decimal Cash{get;set;} public decimal RealizedPnl{get;set;} public DateTimeOffset UpdatedAt{get;set;} public long Version{get;set;} }
public sealed class OrderRecord { public Guid Id{get;set;} public string IdempotencyKey{get;set;}=""; public string Symbol{get;set;}=""; public string? InstrumentToken{get;set;} public string Side{get;set;}=""; public int Quantity{get;set;} public decimal LimitPrice{get;set;} public string StrategyVersion{get;set;}=""; public DateTimeOffset CreatedAt{get;set;} public string ExecutionMode{get;set;}="paper"; public string Status{get;set;}="created"; }
public sealed class FillRecord { public Guid Id{get;set;} public Guid OrderId{get;set;} public string Symbol{get;set;}=""; public string Side{get;set;}=""; public int Quantity{get;set;} public decimal FillPrice{get;set;} public DateTimeOffset FilledAt{get;set;} public string ExecutionProvider{get;set;}="paper"; }
public sealed class PositionRecord { public Guid Id{get;set;} public Guid PortfolioId{get;set;} public string Symbol{get;set;}=""; public string? InstrumentToken{get;set;} public int Quantity{get;set;} public decimal AverageEntryPrice{get;set;} public decimal CurrentMarketPrice{get;set;} public decimal? StopLoss{get;set;} public DateTimeOffset OpenedAt{get;set;} public DateTimeOffset UpdatedAt{get;set;} }
public sealed class AlertRecord { public Guid Id{get;set;} public Guid? PositionId{get;set;} public string? Symbol{get;set;} public string Rule{get;set;}=""; public string Severity{get;set;}=""; public string Message{get;set;}=""; public string EvaluationBucket{get;set;}=""; public DateTimeOffset CreatedAt{get;set;} }
public sealed class MarketDataSnapshotRecord { public Guid Id{get;set;} public string Symbol{get;set;}=""; public string? InstrumentToken{get;set;} public string Provider{get;set;}=""; public string Exchange{get;set;}=""; public DateTimeOffset ProviderTimestamp{get;set;} public DateTimeOffset ReceivedAt{get;set;} public decimal Open{get;set;} public decimal High{get;set;} public decimal Low{get;set;} public decimal Close{get;set;} public decimal LastTradedPrice{get;set;} public long Volume{get;set;} }
public sealed class HistoricalCandleRecord { public Guid Id{get;set;} public string Symbol{get;set;}=""; public string InstrumentToken{get;set;}=""; public string Interval{get;set;}=""; public DateTimeOffset Timestamp{get;set;} public decimal Open{get;set;} public decimal High{get;set;} public decimal Low{get;set;} public decimal Close{get;set;} public long Volume{get;set;} public string Source{get;set;}=""; public DateTimeOffset ReceivedAt{get;set;} }
public sealed class BacktestRunRecord { public Guid Id{get;set;} public string Symbol{get;set;}=""; public string Interval{get;set;}=""; public DateTimeOffset Start{get;set;} public DateTimeOffset End{get;set;} public decimal StartingCash{get;set;} public int QuantityPerTrade{get;set;} public decimal FeeRate{get;set;} public decimal SlippageBasisPoints{get;set;} public string StrategyVersion{get;set;}=""; public string ResultJson{get;set;}=""; public DateTimeOffset CreatedAt{get;set;} }
public sealed class BacktestTradeAuditRecord { public Guid Id{get;set;} public Guid BacktestRunId{get;set;} public DateTimeOffset Timestamp{get;set;} public string Side{get;set;}=""; public int Quantity{get;set;} public decimal Price{get;set;} public decimal Fee{get;set;} public string RiskDecision{get;set;}=""; public string? RiskReason{get;set;} }
public sealed class BacktestRiskAuditRecord { public Guid Id{get;set;} public Guid BacktestRunId{get;set;} public DateTimeOffset Timestamp{get;set;} public string Decision{get;set;}=""; public string? Reason{get;set;} public decimal AvailableCash{get;set;} public int RequestedQuantity{get;set;} }
public sealed class PaperTradingEventAuditRecord { public Guid Id{get;set;} public Guid SessionId{get;set;} public string EventId{get;set;}=""; public Guid OrderId{get;set;} public string Symbol{get;set;}=""; public int Quantity{get;set;} public string RiskDecision{get;set;}=""; public string RiskReason{get;set;}=""; public decimal? FillPrice{get;set;} public DateTimeOffset CreatedAt{get;set;} }
public sealed class PredictionRecordEntity { public Guid Id{get;set;} public string Symbol{get;set;}=""; public string Horizon{get;set;}=""; public decimal ExpectedReturn{get;set;} public decimal ProbabilityPositive{get;set;} public decimal Confidence{get;set;} public string ModelVersion{get;set;}=""; public DateTimeOffset DataTimestamp{get;set;} public DateTimeOffset RecordedAt{get;set;} }
public sealed class PredictionOutcomeEntity { public Guid PredictionId{get;set;} public decimal ActualReturn{get;set;} public DateTimeOffset OutcomeTimestamp{get;set;} }
