using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using AiTrading.Infrastructure.Persistence;

#nullable disable

namespace AiTrading.Infrastructure.Persistence.Migrations;

[DbContext(typeof(TradingDbContext))]
partial class TradingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
        modelBuilder.Entity<PortfolioRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<decimal>("Cash").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("RealizedPnl").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetime(6)"); b.Property<long>("Version").HasColumnType("bigint"); b.HasKey("Id"); b.HasIndex("Version"); b.ToTable("portfolios"); });
        modelBuilder.Entity<OrderRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<string>("IdempotencyKey").HasMaxLength(128).HasColumnType("varchar(128)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("InstrumentToken").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("Side").HasMaxLength(16).HasColumnType("varchar(16)"); b.Property<int>("Quantity").HasColumnType("int"); b.Property<decimal>("LimitPrice").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<string>("StrategyVersion").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetime(6)"); b.Property<string>("ExecutionMode").HasMaxLength(16).HasColumnType("varchar(16)"); b.Property<string>("Status").HasMaxLength(32).HasColumnType("varchar(32)"); b.HasKey("Id"); b.HasIndex("IdempotencyKey").IsUnique(); b.ToTable("orders"); });
        modelBuilder.Entity<FillRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<Guid>("OrderId").HasColumnType("char(36)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("Side").HasMaxLength(16).HasColumnType("varchar(16)"); b.Property<int>("Quantity").HasColumnType("int"); b.Property<decimal>("FillPrice").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<DateTimeOffset>("FilledAt").HasColumnType("datetime(6)"); b.Property<string>("ExecutionProvider").HasMaxLength(32).HasColumnType("varchar(32)"); b.HasKey("Id"); b.HasIndex("OrderId").IsUnique(); b.ToTable("fills"); });
        modelBuilder.Entity<PositionRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<Guid>("PortfolioId").HasColumnType("char(36)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("InstrumentToken").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<int>("Quantity").HasColumnType("int"); b.Property<decimal>("AverageEntryPrice").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("CurrentMarketPrice").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal?>("StopLoss").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<DateTimeOffset>("OpenedAt").HasColumnType("datetime(6)"); b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetime(6)"); b.HasKey("Id"); b.HasIndex("PortfolioId", "Symbol").IsUnique(); b.ToTable("positions"); });
        modelBuilder.Entity<AlertRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<Guid?>("PositionId").HasColumnType("char(36)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("Rule").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<string>("Severity").HasMaxLength(16).HasColumnType("varchar(16)"); b.Property<string>("Message").HasMaxLength(1000).HasColumnType("varchar(1000)"); b.Property<string>("EvaluationBucket").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetime(6)"); b.HasKey("Id"); b.HasIndex("PositionId", "Rule", "EvaluationBucket").IsUnique(); b.ToTable("alerts"); });
        modelBuilder.Entity<MarketDataSnapshotRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("InstrumentToken").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("Provider").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<string>("Exchange").HasMaxLength(32).HasColumnType("varchar(32)"); b.Property<DateTimeOffset>("ProviderTimestamp").HasColumnType("datetime(6)"); b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("datetime(6)"); b.Property<decimal>("Open").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("High").HasPrecision(20, 4).HasColumnType("decimal(20,4"); b.Property<decimal>("Low").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("Close").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("LastTradedPrice").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<long>("Volume").HasColumnType("bigint"); b.HasKey("Id"); b.HasIndex("Symbol", "ProviderTimestamp"); b.ToTable("market_data_snapshots"); });
        modelBuilder.Entity<HistoricalCandleRecord>(b => { b.Property<Guid>("Id").HasColumnType("char(36)"); b.Property<string>("Symbol").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("InstrumentToken").HasMaxLength(100).HasColumnType("varchar(100)"); b.Property<string>("Interval").HasMaxLength(16).HasColumnType("varchar(16)"); b.Property<DateTimeOffset>("Timestamp").HasColumnType("datetime(6)"); b.Property<decimal>("Open").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("High").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("Low").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<decimal>("Close").HasPrecision(20, 4).HasColumnType("decimal(20,4)"); b.Property<long>("Volume").HasColumnType("bigint"); b.Property<string>("Source").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("datetime(6)"); b.HasKey("Id"); b.HasIndex("Symbol", "InstrumentToken", "Interval", "Timestamp", "Source").IsUnique(); b.ToTable("historical_candles"); });
        modelBuilder.Entity<FillRecord>().HasOne<OrderRecord>().WithMany().HasForeignKey("OrderId").OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<PositionRecord>().HasOne<PortfolioRecord>().WithMany().HasForeignKey("PortfolioId").OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<AlertRecord>().HasOne<PositionRecord>().WithMany().HasForeignKey("PositionId").OnDelete(DeleteBehavior.SetNull);
    }
}
