export interface HealthStatus{status:string;mode:'paper'|string;marketProvider:string;aiProvider?:string;persistence:boolean}
export interface PositionSnapshot{id:string;symbol:string;quantity:number;averageEntryPrice:number;stopLoss?:number}
export interface PortfolioSnapshot{cash:number;positions?:PositionSnapshot[];unrealizedPnl?:number;realizedPnl?:number;[key:string]:unknown}
export interface AlertSnapshot{key:string;severity:'Info'|'Warning'|'High'|'Critical'|string;message:string;createdAt:string;symbol?:string}
export interface MarketQuote{symbol:string;exchange:string;instrumentToken:string;timestamp:string;open:number;high:number;low:number;close:number;lastTradedPrice:number;volume:number;source:string;[key:string]:unknown}
export interface Recommendation{symbol:string;action:'Buy'|'Hold'|'Sell'|'NoDecision'|string;referencePrice:number;expectedReturn?:number;confidence:number;horizonDays:number;supportingSignals:string[];riskFactors:string[];generatedAt:string;strategyVersion:string;[key:string]:unknown}
export interface AiResearchRequest{symbol:string;question:string;evidence:string[]}
export interface AiResearchResult{provider:string;summary:string;risks:string[];confidence:number;generatedAt:string}
export interface RiskResult{decision:'Approved'|'RiskBlocked'|'InsufficientData'|string;reason?:string|null}
export interface FillSnapshot{orderId:string;symbol:{value:string;instrumentToken?:string|null};side:'Buy'|'Sell'|string;quantity:number;price:number;timestamp:string;source:string}
export interface PaperTradeResult{risk:RiskResult;fill?:FillSnapshot|null}
export interface BacktestRequest{symbol:{value:string;instrumentToken?:string|null};interval:string;start:string;end:string;configuration:{startingCash:number;quantityPerTrade:number;feeRate:number;slippageBasisPoints:number;strategyVersion:string}}
export interface BacktestTrade{timestamp:string;side:string;quantity:number;price:number;fee:number;riskDecision:string;riskReason?:string|null}
export interface BacktestRiskEvent{timestamp:string;decision:string;reason?:string|null;availableCash:number;requestedQuantity:number}
export interface BacktestEquityPoint{timestamp:string;cash:number;positionValue:number;equity:number}
export interface BacktestResult{startingCash:number;endingCash:number;returnPercent:number;maxDrawdownPercent:number;trades:BacktestTrade[];equityCurve:BacktestEquityPoint[];riskEvents:BacktestRiskEvent[];simulationOnly?:boolean;winCount?:number;lossCount?:number}
export interface BacktestResponse{runId:string;status:string;result:BacktestResult;simulationLabel:string}
export interface EvaluationMetrics{total:number;evaluated:number;wins:number;losses:number;directionalAccuracy:number;cumulativeReturn:number;maxDrawdown:number;unitPnl:number}
export interface RecoveryPosition{id:string;portfolioId:string;symbol:{value:string;instrumentToken?:string|null}|string;originalQuantity:number;remainingQuantity:number;averageEntryPrice:number;lastCoverPrice?:number|null;realizedPnl:number;state:string;version:number;createdAt:string;updatedAt:string}
export interface RecoveryCover{id:string;positionId:string;idempotencyKey:string;coverPrice:number;coverQuantity:number;realizedPnl:number;resultingPositionVersion:number;createdAt:string}
export interface RecoveryReconciliation{isConsistent:boolean;reason:string}
export interface RecoveryDiagnostic{position:RecoveryPosition;covers:RecoveryCover[];reconciliation:RecoveryReconciliation}
export interface ApiError{errorCode?:string;message?:string;risk?:RiskResult;[key:string]:unknown}
