import {CommonModule} from '@angular/common';
import {Component,inject} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {RouterLink} from '@angular/router';

interface CoverResult{executionMode:string;position:{id:string;remainingQuantity:number;lastCoverPrice?:number|null;realizedPnl:number;state:string;version:number}}

@Component({selector:'app-paper-short-cover',standalone:true,imports:[CommonModule,RouterLink],template:`<section class="cover"><header><div><p class="eyebrow">PAPER / SHORT LIFECYCLE</p><h1>Cover Paper Short</h1><p>Explicit user/API initiated cover only. No automatic liquidation or live broker execution.</p></div><span class="safety">PAPER ONLY</span></header><form (submit)="cover($event)"><label>Position ID<input [value]="positionId" (input)="positionId=$any($event.target).value" required></label><label>Cover price<input type="number" [value]="coverPrice" (input)="coverPrice=+$any($event.target).value" min="0.000001" step="0.000001" required></label><label>Cover quantity<input type="number" [value]="coverQuantity" (input)="coverQuantity=+$any($event.target).value" min="1" step="1" required></label><label>Expected version<input type="number" [value]="expectedVersion" (input)="expectedVersion=+$any($event.target).value" min="0" step="1" required></label><label>Idempotency key<input [value]="idempotencyKey" (input)="idempotencyKey=$any($event.target).value" required></label><button type="submit">Cover paper short</button></form>@if(message){<div class="notice">{{message}}</div>}@if(result){<section class="result"><strong>{{result.position.state}}</strong><span>Remaining: {{result.position.remainingQuantity}}</span><span>Last cover: {{result.position.lastCoverPrice ?? '—'}}</span><span>Realized P&amp;L: {{result.position.realizedPnl}}</span><span>Version: {{result.position.version}}</span><a [routerLink]="['/recovery']" [queryParams]="{positionId:result.position.id}">Inspect recovery diagnostics</a></section>}<aside><strong>Safety boundary.</strong> Cover requests require an explicit position, price, quantity, expected version, and idempotency key. Server-side persistence, concurrency, and idempotency rules remain authoritative.</aside></section>`,styles:[`.cover{max-width:760px;margin:2rem auto;padding:1.5rem}.cover form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:1.5rem 0}header{display:flex;justify-content:space-between;gap:1rem}.eyebrow{font-size:.72rem;letter-spacing:.08em}.safety{border:1px solid currentColor;padding:.4rem .7rem;font-size:.72rem}label{display:grid;gap:.35rem;font-size:.85rem}input{padding:.65rem;border:1px solid #ccd2dc;border-radius:7px}button{grid-column:1/-1;padding:.7rem;border:0;border-radius:7px}.notice,.result,aside{border:1px solid #d9dee7;border-radius:9px;padding:1rem}.result{display:grid;gap:.35rem}.result strong{font-size:1.1rem}.result a{margin-top:.4rem}.result a:focus-visible{outline:2px solid currentColor;outline-offset:2px}aside{margin-top:1rem}@media(max-width:650px){header{display:block}.cover form{display:block}.cover form label{margin-bottom:.8rem}}`]})
export class PaperShortCoverComponent{private readonly http=inject(HttpClient);private readonly base='/api';positionId='';coverPrice=0;coverQuantity=1;expectedVersion=0;idempotencyKey='';message='';result:CoverResult|null=null;cover(e:Event){e.preventDefault();this.result=null;this.message='Covering paper short…';this.http.post<CoverResult>(`${this.base}/paper-shorts/${this.positionId.trim()}/cover`,{coverPrice:this.coverPrice,coverQuantity:this.coverQuantity,expectedVersion:this.expectedVersion},{headers:{'Idempotency-Key':this.idempotencyKey.trim()}}).subscribe({next:r=>{this.result=r;this.message=`Paper short cover: ${r.position.state}.`},error:x=>{this.message=x?.error?.message??'Paper short cover rejected.'}})}}
